#ifndef __BIN_MODEL_DATA_H__
#define __BIN_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>
extern const unsigned char g_bin_model_data[];
extern const unsigned int g_bin_model_data_len;

#endif
